version: '3.8'

services:
  meme-generator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "2233:2233"
    volumes:
      - ./data:/data
      - ./config:/app/config
    environment:
      - TZ=Asia/Shanghai
      - LOAD_BUILTIN_MEMES=true
      - MEME_DIRS=["/data/contrib", "/data/emoji"]
      - MEME_DISABLED_LIST=[]
      - GIF_MAX_SIZE=10.0
      - GIF_MAX_FRAMES=100
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2233/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  config: