version: '3'
services:
  meme-generator:
    image: meetwq/meme-generator:main
    container_name: meme-generator
    restart: always
    ports:
      - "2233:2233"
    volumes:
    	#额外表情路径
      - <YOUR_DATA_DIR>:/data
    environment:
      - MEME_DIRS='["/data/memes"]'
      - MEME_DISABLED_LIST='[]'
      - GIF_MAX_SIZE=10.0
      - GIF_MAX_FRAMES=100
      - BAIDU_TRANS_APPID=<YOUR_BAIDU_TRANS_APPID>
      - BAIDU_TRANS_APIKEY=<YOUR_BAIDU_TRANS_APIKEY>
      - LOG_LEVEL=INFO